package application.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import application.model.Livro;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

public class PrincipalController {
	@FXML
	private AnchorPane taListaLivros1;
	@FXML
	private Button buscaLivro;
	@FXML
	private Button copiaLivro;
	@FXML
	private Button inserirLivro;
	@FXML
	private Button attLivro;
	@FXML
	private Button delLivro;
	@FXML
	private Button listarLivro;
	
	private TextField tfIsbnLivro;
	private TextField tfTituloLivro;
	private TextField tfAutorLivro;
	private TextArea taListaLivros;
	
	@FXML
	public void acaoLivro(ActionEvent event) {
		String cmd = event.getSource().toString();
		
		LivroController livroController = new LivroController(tfIsbnLivro, tfTituloLivro, tfAutorLivro, taListaLivros);
		
		if ((cmd.contains("Inserir") || cmd.contains("Atualizar")) && 
				(tfIsbnLivro.getText().isEmpty() || tfTituloLivro.getText().isEmpty() || tfAutorLivro.getText().isEmpty())) {
			JOptionPane.showMessageDialog(null, "Preencha os campos.", "ERRO", JOptionPane.ERROR_MESSAGE);
		} else {
			if (cmd.contains("Excluir") || (cmd.contains("Buscar") || (cmd.contains("tfIsbnLivro")
					&& tfIsbnLivro.getText().isEmpty()))) {
				JOptionPane.showMessageDialog(null, "Preencha o ISBN.", "ERRO", JOptionPane.ERROR_MESSAGE);
			} else {
				try {
					if (cmd.contains("Listar")) {
						livroController.buscarLivros();
					} else {
						Livro l = new Livro();
						l.setISBN(Integer.parseInt(tfIsbnLivro.getText()));
						l.setTitulo(tfTituloLivro.getText());
						l.setAutor(tfAutorLivro.getText());
						if (cmd.contains("Inserir")) {
							livroController.inserirLivro(l);
						} else if (cmd.contains("Atualizar")) {
							livroController.atualizarLivro(l);
						} else if (cmd.contains("Excluir")) {
							livroController.excluirLivro(l);
						} else if (cmd.contains("Buscar") || cmd.contains("tfIsbnLivro")) {
							livroController.buscarLivro(l);
						}
					}
				} catch (ClassNotFoundException | SQLException e) {
					JOptionPane.showMessageDialog(null, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
					e.printStackTrace();
				}
			}
		}
	}
	@FXML
	public void copiaLivro(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void buscaLivro(ActionEvent event) {
		// TODO Autogenerated
	}
	public TextArea getTaListaLivros() {
		return taListaLivros;
	}
	public void setTaListaLivros(TextArea taListaLivros) {
		this.taListaLivros = taListaLivros;
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
}
