SELECT LTRIM(RTRIM(SUBSTRING('Banco de Dados',6,4))) AS sub

SELECT GETDATE() AS hoje

SELECT DAY(GETDATE()) AS dia
SELECT MONTH (GETDATE()) AS mes
SELECT YEAR (GETDATE()) AS ano

SELECT DAY(GETDATE()) AS dia, MONTH (GETDATE()) AS mes, YEAR (GETDATE()) AS ano

SELECT DATEPART(WEEK,GETDATE()) AS semana_do_ano

SELECT DATEPART(DAYOFYEAR, GETDATE()) AS dias_do_ano;

--DATEDIFF & DATEADD

SELECT DATEDIFF(DAY, '1998-05-26',GETDATE()) AS Ex_30

SELECT DATEADD(DAY, 7, GETDATE()) AS daqui_sete_dias

SELECT DATEADD(MONTH, 10, GETDATE()) AS daqui_dez_meses