CREATE DATABASE ExDDLDML1
GO
USE ExDDLDML1

CREATE TABLE USERS
( id		INT			IDENTITY(1,1)	NOT NULL,
nome		VARCHAR(45)					NOT NULL,
username	VARCHAR(45)	UNIQUE			NOT NULL,
password	VARCHAR(45)					NOT NULL		DEFAULT '123mudar',
email		VARCHAR(45)					NOT NULL,
PRIMARY KEY(id) );

CREATE TABLE PROJECTS
( id		INT				IDENTITY(10001,1)	NOT NULL,
name		VARCHAR(45)							NOT NULL,
description	VARCHAR(45)							NOT NULL,
date		VARCHAR(45)							NOT NULL		CHECK (date > '2014-09-01'),
PRIMARY KEY(id) );

CREATE TABLE USER_HAS_PROJECTS
( users_id	INT			NOT NULL,
projects_id	INT			NOT NULL,
PRIMARY KEY (users_id, projects_id),
FOREIGN KEY (users_id) REFERENCES USERS(id),
FOREIGN KEY (projects_id) REFERENCES PROJECTS(id) );

